version: '2'

networks:
  laravel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 171.16.0.0/16
          gateway: 171.16.238.1

volumes: 
  dbvolume:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-laravel-scaffolding
    ports:
      - "8901:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      laravel:
        ipv4_address: 171.16.0.1

  mysql:
    image: mysql:5.7.29
    container_name: mysql-laravel-scaffolding
    restart: unless-stopped
    tty: true
    ports:
      - "8902:3306"
    volumes: 
      - dbvolume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      laravel:
        ipv4_address: 171.16.0.2

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-laravel-scaffolding
    volumes:
      - .:/var/www/html
    ports:
      - "8903:9000"
    networks:
      laravel:
        ipv4_address: 171.16.0.3

  # npm:
  #   image: node:13.7
  #   container_name: npm
  #   volumes:
  #     - .:/var/www/html
  #   working_dir: /var/www/html
  #   entrypoint: ['npm']

